version: '3.6'

services:
  hms:
    build: .
    command: 
      - "yarn"
      - "dev"
    volumes:
      - "./src:/app/src"
    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"